/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root'
import { Route as layoutRouteImport } from './routes/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as R2colLayoutRouteImport } from './routes/(2col)/layout'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as R2colSettingsIndexRouteImport } from './routes/(2col)/settings/index'
import { Route as R2colMessagesIndexRouteImport } from './routes/(2col)/messages/index'
import { Route as R2colMembersIndexRouteImport } from './routes/(2col)/members/index'
import { Route as R2colManagementsIndexRouteImport } from './routes/(2col)/managements/index'
import { Route as R2colCalendarIndexRouteImport } from './routes/(2col)/calendar/index'
import { Route as indexRouteImport } from './routes/index'
import { Route as userIndexRouteImport } from './routes/$user/index'
import { Route as userStatusIdIndexRouteImport } from './routes/$user/status/$id/index'

const layoutRoute = layoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R2colLayoutRoute = R2colLayoutRouteImport.update({
  id: '/_2col-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const R2colSettingsIndexRoute = R2colSettingsIndexRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => R2colLayoutRoute,
} as any)
const R2colMessagesIndexRoute = R2colMessagesIndexRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => R2colLayoutRoute,
} as any)
const R2colMembersIndexRoute = R2colMembersIndexRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => R2colLayoutRoute,
} as any)
const R2colManagementsIndexRoute = R2colManagementsIndexRouteImport.update({
  id: '/managements',
  path: '/managements',
  getParentRoute: () => R2colLayoutRoute,
} as any)
const R2colCalendarIndexRoute = R2colCalendarIndexRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => R2colLayoutRoute,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRoute,
} as any)
const userIndexRoute = userIndexRouteImport.update({
  id: '/$user/',
  path: '/$user/',
  getParentRoute: () => layoutRoute,
} as any)
const userStatusIdIndexRoute = userStatusIdIndexRouteImport.update({
  id: '/$user/status/$id',
  path: '/$user/status/$id',
  getParentRoute: () => layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/calendar': typeof R2colCalendarIndexRoute
  '/managements': typeof R2colManagementsIndexRoute
  '/members': typeof R2colMembersIndexRoute
  '/messages': typeof R2colMessagesIndexRoute
  '/settings': typeof R2colSettingsIndexRoute
  '/login': typeof authLoginIndexRoute
  '/$user': typeof userIndexRoute
  '/$user/status/$id': typeof userStatusIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/calendar': typeof R2colCalendarIndexRoute
  '/managements': typeof R2colManagementsIndexRoute
  '/members': typeof R2colMembersIndexRoute
  '/messages': typeof R2colMessagesIndexRoute
  '/settings': typeof R2colSettingsIndexRoute
  '/login': typeof authLoginIndexRoute
  '/$user': typeof userIndexRoute
  '/$user/status/$id': typeof userStatusIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_2col-layout': typeof R2colLayoutRouteWithChildren
  '/_auth': typeof authLayoutRouteWithChildren
  '/_layout': typeof layoutRouteWithChildren
  '/_layout/': typeof indexRoute
  '/_2col-layout/calendar': typeof R2colCalendarIndexRoute
  '/_2col-layout/managements': typeof R2colManagementsIndexRoute
  '/_2col-layout/members': typeof R2colMembersIndexRoute
  '/_2col-layout/messages': typeof R2colMessagesIndexRoute
  '/_2col-layout/settings': typeof R2colSettingsIndexRoute
  '/_auth/login': typeof authLoginIndexRoute
  '/_layout/$user/': typeof userIndexRoute
  '/_layout/$user/status/$id': typeof userStatusIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/managements'
    | '/members'
    | '/messages'
    | '/settings'
    | '/login'
    | '/$user'
    | '/$user/status/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/managements'
    | '/members'
    | '/messages'
    | '/settings'
    | '/login'
    | '/$user'
    | '/$user/status/$id'
  id:
    | '__root__'
    | '/_2col-layout'
    | '/_auth'
    | '/_layout'
    | '/_layout/'
    | '/_2col-layout/calendar'
    | '/_2col-layout/managements'
    | '/_2col-layout/members'
    | '/_2col-layout/messages'
    | '/_2col-layout/settings'
    | '/_auth/login'
    | '/_layout/$user/'
    | '/_layout/$user/status/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R2colLayoutRoute: typeof R2colLayoutRouteWithChildren
  authLayoutRoute: typeof authLayoutRouteWithChildren
  layoutRoute: typeof layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_2col-layout': {
      id: '/_2col-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof R2colLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/_2col-layout/settings': {
      id: '/_2col-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof R2colSettingsIndexRouteImport
      parentRoute: typeof R2colLayoutRoute
    }
    '/_2col-layout/messages': {
      id: '/_2col-layout/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof R2colMessagesIndexRouteImport
      parentRoute: typeof R2colLayoutRoute
    }
    '/_2col-layout/members': {
      id: '/_2col-layout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof R2colMembersIndexRouteImport
      parentRoute: typeof R2colLayoutRoute
    }
    '/_2col-layout/managements': {
      id: '/_2col-layout/managements'
      path: '/managements'
      fullPath: '/managements'
      preLoaderRoute: typeof R2colManagementsIndexRouteImport
      parentRoute: typeof R2colLayoutRoute
    }
    '/_2col-layout/calendar': {
      id: '/_2col-layout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof R2colCalendarIndexRouteImport
      parentRoute: typeof R2colLayoutRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof layoutRoute
    }
    '/_layout/$user/': {
      id: '/_layout/$user/'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof userIndexRouteImport
      parentRoute: typeof layoutRoute
    }
    '/_layout/$user/status/$id': {
      id: '/_layout/$user/status/$id'
      path: '/$user/status/$id'
      fullPath: '/$user/status/$id'
      preLoaderRoute: typeof userStatusIdIndexRouteImport
      parentRoute: typeof layoutRoute
    }
  }
}

interface R2colLayoutRouteChildren {
  R2colCalendarIndexRoute: typeof R2colCalendarIndexRoute
  R2colManagementsIndexRoute: typeof R2colManagementsIndexRoute
  R2colMembersIndexRoute: typeof R2colMembersIndexRoute
  R2colMessagesIndexRoute: typeof R2colMessagesIndexRoute
  R2colSettingsIndexRoute: typeof R2colSettingsIndexRoute
}

const R2colLayoutRouteChildren: R2colLayoutRouteChildren = {
  R2colCalendarIndexRoute: R2colCalendarIndexRoute,
  R2colManagementsIndexRoute: R2colManagementsIndexRoute,
  R2colMembersIndexRoute: R2colMembersIndexRoute,
  R2colMessagesIndexRoute: R2colMessagesIndexRoute,
  R2colSettingsIndexRoute: R2colSettingsIndexRoute,
}

const R2colLayoutRouteWithChildren = R2colLayoutRoute._addFileChildren(
  R2colLayoutRouteChildren,
)

interface authLayoutRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface layoutRouteChildren {
  indexRoute: typeof indexRoute
  userIndexRoute: typeof userIndexRoute
  userStatusIdIndexRoute: typeof userStatusIdIndexRoute
}

const layoutRouteChildren: layoutRouteChildren = {
  indexRoute: indexRoute,
  userIndexRoute: userIndexRoute,
  userStatusIdIndexRoute: userStatusIdIndexRoute,
}

const layoutRouteWithChildren =
  layoutRoute._addFileChildren(layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R2colLayoutRoute: R2colLayoutRouteWithChildren,
  authLayoutRoute: authLayoutRouteWithChildren,
  layoutRoute: layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
